formato = [
    {"fila": "1", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "SIMPADE - Formato 1"},
    {"fila": "2", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "Información básica del Estudiante"},
    {"fila": "3", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Nombre de la IED:"},
    {"fila": "4", "orden": "1", "tamano": "8", "tipo": "pregunta", "contenido": "Nombre del Estudiante:"},
    {"fila": "4", "orden": "2", "tamano": "4", "tipo": "pregunta", "contenido": "Grado a matricular:"},
    {"fila": "5", "orden": "1", "tamano": "9", "tipo": "pregunta", "contenido": "Número de Identificación:"},
    {"fila": "6", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "Información Individual"},
    {"fila": "7", "orden": "1", "tamano": "6", "tipo": "pregunta", "contenido": "¿El estudiante vive solo?"},
    {"fila": "7", "orden": "2", "tamano": "6", "tipo": "pregunta", "contenido": "¿Embarazo adolescente?"},
    {"fila": "8", "orden": "1", "tamano": "6", "tipo": "pregunta", "contenido": "¿Realiza algún tipo de trabajo remunerado o no remunerado?"},
    {"fila": "8", "orden": "2", "tamano": "6", "tipo": "pregunta", "contenido": "¿Maternidad o paternidad a temprana edad?"},
    {"fila": "9", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Refiere que ha sido víctima de discriminación, agresiones físicas o agresiones verbales en razón a sus expresiones de género, su orientación o identidad sexual? (población LGBTI)"},
    {"fila": "10", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Refiere que ha sido víctima de agresiones físicas, verbales o sexuales por parte de alguien de su entorno educativo o familiar?"},
    {"fila": "11", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Refiere que ha sido víctima de discriminación en razón a:"},
    {"fila": "12", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "LA SIGUIENTE PREGUNTA ES SOLO PARA ESTUDIANTES DE 8° en adelante"},
    {"fila": "13", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Qué desea estudiar?"},
    {"fila": "14", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "Información familiar"},
    {"fila": "15", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Número de personas que viven en el hogar:"},
    {"fila": "16", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "Características de vivienda"},
    {"fila": "17", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Tipo de vivienda:"},
    {"fila": "18", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Tenencia de la vivienda:"},
    {"fila": "19", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Servicios que tiene la vivienda? (Puede seleccionar varias opciones)"},
    {"fila": "20", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "Trayectoria escolar"},
    {"fila": "21", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Tuvo educación preescolar?"},
    {"fila": "22", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Qué grados de preescolar cursó? (Marque todos los que cursó)"},
    {"fila": "23", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Alguna vez se ha retirado del establecimiento educativo sin terminar el año?"},
    {"fila": "24", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Cuánto tiempo, en meses, estuvo por fuera del sistema educativo?"},
    {"fila": "25", "orden": "1", "tamano": "6", "tipo": "pregunta", "contenido": "¿Cuántas veces ha dejado el colegio este año?"},
    {"fila": "25", "orden": "2", "tamano": "6", "tipo": "pregunta", "contenido": "¿Ha repetido años?"},
    {"fila": "26", "orden": "1", "tamano": "6", "tipo": "pregunta", "contenido": "¿Cuántas veces ha repetido años?"},
    {"fila": "26", "orden": "2", "tamano": "6", "tipo": "pregunta", "contenido": "¿Está repitiendo el grado actual?"},
    {"fila": "27", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Antecedentes disciplinarios de la vida académica:"},
    {"fila": "28", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Asistencia promedio del año anterior:"},
    {"fila": "29", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Presenta alteraciones en el desarrollo o dificultades de aprendizaje diagnosticadas por un especialista?"},
    {"fila": "30", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "¿Estuvo vinculado a una modalidad de educación inicial antes de ingresar a preescolar?"},
    {"fila": "31", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Estrategias que debería tener el estudiante (Seleccione máximo 2)"},
    {"fila": "32", "orden": "1", "tamano": "12", "tipo": "texto", "contenido": "INFORMACIÓN COMPLEMENTARIA (Acudiente)"},
    {"fila": "33", "orden": "1", "tamano": "6", "tipo": "pregunta", "contenido": "Tipo de documento:"},
    {"fila": "33", "orden": "2", "tamano": "6", "tipo": "pregunta", "contenido": "Número documento:"},
    {"fila": "34", "orden": "2", "tamano": "12", "tipo": "pregunta", "contenido": "Nombres y Apellidos:"},
    {"fila": "35", "orden": "2", "tamano": "12", "tipo": "pregunta", "contenido": "Nivel Educativo:"},
    {"fila": "36", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Asiste a reuniones distintas a las de la entrega de boletines:"},
    {"fila": "37", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Asiste a entrega de informes académicos:"},
    {"fila": "38", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Tipo de Empleo:"},
    {"fila": "39", "orden": "1", "tamano": "12", "tipo": "pregunta", "contenido": "Frecuencia con la que ha cambiado de domicilio en el último año:"},
]
