preguntas = [
    {"tipo": "texto", "titulo": "Nombre de la IED:"},
    {"tipo": "texto", "titulo": "Nombre del Estudiante:"},
    {"tipo": "texto", "titulo": "Grado a matricular:"},
    {"tipo": "texto", "titulo": "N\u00famero de Identificaci\u00f3n:"},
    {"tipo": "opcion", "titulo": "\u00bfEl estudiante vive solo?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfEmbarazo adolescente?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfRealiza alg\u00fan tipo de trabajo remunerado o no remunerado?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfMaternidad o paternidad a temprana edad?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfRefiere que ha sido v\u00edctima de discriminaci\u00f3n, agresiones f\u00edsicas o agresiones verbales en raz\u00f3n a sus expresiones de g\u00e9nero, su orientaci\u00f3n o identidad sexual? (poblaci\u00f3n LGBTI)", "opciones": ["SI", "NO", "NO APLICA"]},
    {"tipo": "opcion", "titulo": "\u00bfRefiere que ha sido v\u00edctima de agresiones f\u00edsicas, verbales o sexuales por parte de alguien de su entorno educativo o familiar?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfRefiere que ha sido v\u00edctima de discriminaci\u00f3n en raz\u00f3n a:", "opciones": ["Discapacidad", "Su ritmo de aprendizaje", "Apariencia f\u00edsica", "Religi\u00f3n", "Pertenencia \u00e9tnica", "Caracter\u00edsticas Familiares", "Otras"], "varias": True},
    {"tipo": "texto", "titulo": "\u00bfQu\u00e9 desea estudiar?"},
    {"tipo": "texto", "titulo": "N\u00famero de personas que viven en el hogar:", "enteros": True},
    {"tipo": "opcion", "titulo": "Tipo de vivienda:", "opciones": ["CASA", "APARTAMENTO", "CUARTOS", "OTROS (CARPAS, ALBERGUES, ETC)"]},
    {"tipo": "opcion", "titulo": "Tenencia de la vivienda:", "opciones": ["PROPIA", "ARRIENDO", "PROPIA CON CR\u00c9DITO", "USUFRUCTO"]},
    {"tipo": "opcion", "titulo": "\u00bfServicios que tiene la vivienda? (Puede seleccionar varias opciones)", "opciones": ["AGUA", "ALCANTARILLADO", "GAS", "TEL\u00c9FONO", "INTERNET", "ENERG\u00cdA", "RECOLECCI\u00d3N DE BASURAS", "ENERG\u00cdA ALTERNATIVA RENOVABLE"], "varias": True},
    {"tipo": "opcion", "titulo": "\u00bfTuvo educaci\u00f3n preescolar?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfQu\u00e9 grados de preescolar curs\u00f3? (Marque todos los que curs\u00f3)", "opciones": ["PREJARD\u00cdN", "JARD\u00cdN", "TRANSICI\u00d3N"], "varias": True},
    {"tipo": "opcion", "titulo": "\u00bfAlguna vez se ha retirado del establecimiento educativo sin terminar el a\u00f1o?", "opciones": ["SI", "NO"]},
    {"tipo": "texto", "titulo": "\u00bfCu\u00e1nto tiempo, en meses, estuvo por fuera del sistema educativo?", "enteros": True},
    {"tipo": "texto", "titulo": "\u00bfCu\u00e1ntas veces ha dejado el colegio este a\u00f1o?", "enteros": True},
    {"tipo": "opcion", "titulo": "\u00bfHa repetido a\u00f1os?", "opciones": ["SI", "NO"]},
    {"tipo": "texto", "titulo": "\u00bfCu\u00e1ntas veces ha repetido a\u00f1os?", "enteros": True},
    {"tipo": "opcion", "titulo": "\u00bfEst\u00e1 repitiendo el grado actual?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "Antecedentes disciplinarios de la vida acad\u00e9mica:", "opciones": ["Llamados de atenci\u00f3n", "Suspensi\u00f3n", "Llamados de atenci\u00f3n Y Suspensi\u00f3n", "No Aplica"]},
    {"tipo": "opcion", "titulo": "Asistencia promedio del a\u00f1o anterior:", "opciones": ["ALTA (80% O MAS)", "MEDIA (ENTRE 50% Y 80%)", "BAJA (MENOR AL 50%)", "NO APLICA"]},
    {"tipo": "opcion", "titulo": "\u00bfPresenta alteraciones en el desarrollo o dificultades de aprendizaje diagnosticadas por un especialista?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "\u00bfEstuvo vinculado a una modalidad de educaci\u00f3n inicial antes de ingresar a preescolar?", "opciones": ["SI", "NO"]},
    {"tipo": "opcion", "titulo": "Estrategias que deber\u00eda tener el estudiante (Seleccione m\u00e1ximo 2)", "opciones": ["SUBSIDIOS CONDICIONADOS A LA ASISTENCIA ESCOLAR", "\u00daTILES ESCOLARES", "JORNADA ESCOLAR COMPLEMENTARIA", "ATENCI\u00d3N INTEGRAL", "VESTUARIO ESCOLAR", "TRANSPORTE ESCOLAR", "PAE EMERGENCIA"], "varias": True},
    {"tipo": "recurso", "titulo": "INFORMACI\u00d3N COMPLEMENTARIA (Acudiente)"},
    {"tipo": "texto", "titulo": "Tipo de documento:"},
    {"tipo": "texto", "titulo": "N\u00famero documento:"},
    {"tipo": "texto", "titulo": "Nombres y Apellidos:"},
    {"tipo": "opcion", "titulo": "Nivel Educativo:", "opciones": ["Sin Educaci\u00f3n", "Primaria incompleta", "Primaria completa", "Media Incompleta", "Media completa", "Superior Incompleta", "Superior Completa", "Posgrado"]},
    {"tipo": "opcion", "titulo": "Asiste a reuniones distintas a las de la entrega de boletines:", "opciones": ["Siempre", "Casi Siempre", "Algunas veces", "Casi nunca", "Nunca"]},
    {"tipo": "opcion", "titulo": "Asiste a entrega de informes acad\u00e9micos:", "opciones": ["Siempre", "Casi Siempre", "Algunas veces", "Casi nunca", "Nunca"]},
    {"tipo": "opcion", "titulo": "Tipo de Empleo:", "opciones": ["Temporal", "Permanente", "No tiene"]},
    {"tipo": "opcion", "titulo": "Frecuencia con la que ha cambiado de domicilio en el \u00faltimo a\u00f1o:", "opciones": ["No ha cambiado", "Entre 1 y 2 veces", "Entre 3 y 4 veces", "M\u00e1s de 4 veces"]},
]
